package com.sample

import com.sample.DroolsTest.Okienko;
import com.sample.DroolsTest.Odpowiedz;

rule "Do you tend to live in the moment?"
	when
		o : Okienko("Would you rather work solo or with a team?".equals(getQuestion()))
		odp : Odpowiedz("Would you rather work solo or with a team?".equals(gettekst()) && getodp() == Okienko.TAK)
	then
		o.nextQuestion("Yes", "No", "Do you tend to live in the moment?");
		update(o);
end

rule "Do you folow your gut when it comes to life choices?"
	when
		o : Okienko("Would you rather work solo or with a team?".equals(getQuestion()))
		odp : Odpowiedz("Would you rather work solo or with a team?".equals(gettekst()) && getodp() == Okienko.NIE)
	then
		o.nextQuestion("Yes", "No", "Do you folow your gut when it comes to life choices?");
		update(o);
end
